blowfish:
  port: 3000

###
#   Database Settings
###
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:h2:mem:blowfish;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:mem:medusa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:file:~/phoenix
    platform: h2
    username: sa
    password: test
    driverClassName: org.h2.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 60000
      maximum-pool-size: 5
      connection-test-query: SELECT 1
      minimum-idle: 1
      pool-name: HikariThread
      auto-commit: false
    #tomcat:
    #    max-active: 50
    #    max-idle: 50
    #    testOnBorrow: true
    #    validationQuery: select 1;
    #    validationInterval: 30000
  jpa:
    database: default
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        c3p0:
          max_size: 15
          min_size: 6
          timeout: 2500
          max_statements_per_connection: 10
          idle_test_period: 3000
          acquire_increment: 3
          validate: false
          numHelperThreads: 15
#        connection:
#          provider_class: org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider

# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
  redis:
    cluster-mode: false
    database: 0 # Database index used by the connection factory.
    host: localhost # Redis server host.
    port: 6379 # Redis server port.
    cluster:
      nodes: redis1.4un0o7.ng.0001.euw2.cache.amazonaws.com:6379,redis1-002.4un0o7.0001.euw2.cache.amazonaws.com:6379,redis1-003.4un0o7.0001.euw2.cache.amazonaws.com:6379 # Comma-separated list of host:port pairs.
      max-redirects: 3
    #password: # Login password of the redis server.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 0 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
    timeout: 20000 # Connection timeout in milliseconds.


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


  metrics:
    export:
      delay-millis: 60000
      send-latest: false
#      includes: heap.used,heap.committed,mem,mem.free,threads,datasource.primary.active,datasource.primary.usage,gauge.response.persons,gauge.response.persons.id,gauge.response.persons.remove

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false


endpoints:
  trace:
    sensitive: false

management:
  port: 8081
  trace:
    include: parameters, errors, remote_address, request_headers, response_headers, cookies, authorization_header, path_info, path_translated, context_path, user_principal, query_string, auth_type, session_id, remote_user, time_taken
  security:
    enabled: false

flyway:
  baselineOnMigrate: true

#security.user.name=admin
#security.user.password=secret
#management.security.role=SUPERUSER








